#region Generated by `terra/node/src/rtc/interface/renderers.ts`. DO NOT MODIFY BY HAND.
#endregion

#define AGORA_RTC

using System;
using view_t = System.UInt64;

namespace Agora.Rtc
{
    ///
    /// @ignore
    ///
    public abstract class IMediaRecorder
    {
        ///
        /// @ignore
        ///
        public abstract int SetMediaRecorderObserver(IMediaRecorderObserver callback);

        ///
        /// @ignore
        ///
        public abstract int StartRecording(MediaRecorderConfiguration config);

        ///
        /// @ignore
        ///
        public abstract int StopRecording();

    }
}