#region Generated by `terra/node/src/rtc/interface/renderers.ts`. DO NOT MODIFY BY HAND.
#endregion

#define AGORA_RTC

using System;
using view_t = System.UInt64;

namespace Agora.Rtc
{
    ///
    /// @ignore
    ///
    public abstract class IMusicPlayer : IMediaPlayer
    {
        ///
        /// @ignore
        ///
        public abstract int Open(long songCode, long startPos = 0);

        ///
        /// @ignore
        ///
        public abstract int SetPlayMode(MusicPlayMode mode);

    }
}